reorg

diff --git a/dot-files/bash_profile b/dot-files/bash_profile
--- a/dot-files/bash_profile
+++ b/dot-files/bash_profile
@@ -1,7 +1,22 @@
-source ~/.profile
 # bash_profile: loaded in interactive login shell
+# 
+# Because of this file's existence, neither ~/.bash_login nor ~/.profile
+# will be sourced.
+# This eventually source ~/.bashrc which inturn sources ~/.profile
 
 
-[ -f ~/.bashrc ] && . ~/.bashrc; 
-
-#. "$HOME/.cargo/env"
+# The following sources ~/.bashrc in the interactive login case,
+# because .bashrc isn't sourced for interactive login shells:
+# Example $-: 'himBH'
+#
+case "$-" in 
+    *i*) 
+        if [ -r ~/.bashrc ]; then 
+            . ~/.bashrc
+        else
+            echo "Warn: could not load ~/.bashrc" >&2
+        fi
+    ;;
+    *) echo "Warn: ~/.bashrc, not loades" >&2 
+    ;; 
+esac
